# Generated by Django 3.1.4 on 2021-01-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survivor',
            options={'verbose_name': 'Survivor', 'verbose_name_plural': 'Survivors'},
        ),
    ]
