# Generated by Django 3.1.4 on 2021-01-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210104_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survivor',
            options={},
        ),
    ]
